version: '3'


services:
    django:
        build: .
        command: >
            sh -c "
            python api_news/manage.py migrate --noinput &&
            python api_news/manage.py runserver 0.0.0.0:8000"
        volumes:
            - .:/usr/src/app
        ports:
            - 8000:8000
        depends_on:
            - db
            - redis
        env_file:
            - .env
        networks:
            - some_network
    db:
        image: postgres:13.0-alpine
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        ports:
            - "5432:5432"
        env_file:
            - .env
        networks:
            - some_network
    redis:
        image: 'redis:alpine'
        hostname: redis
        command: redis-server
        networks:
            - some_network
        ports:
            - '6379:6379'
    celery-worker:
        build: .
        command: celery -A api_news worker --loglevel=info
        depends_on:
            - db
            - redis
            - django
        env_file:
            - .env
        networks:
            - some_network
        volumes:
        - ./api_news:/usr/src/app
    celery-beat:
        build: .
        command: celery -A api_news beat --loglevel=info
        depends_on:
            - db
            - redis
            - celery-worker
            - django
        env_file:
            - .env
        networks:
            - some_network
        volumes:
        - ./api_news:/usr/src/app

networks:
    some_network:
        driver: bridge

volumes:
    postgres_data: