version: '3'

services:
    django:
        build: .
        command: python api_news/manage.py runserver 0.0.0.0:8000
        volumes:
        - .:/app/api_news
        ports:
        - 8000:8000
        environment:
        - POSTGRES_NAME=postgres
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
        depends_on:
            - db
    db:
        image: postgres:13.0-alpine
        volumes:
        - postgres_data:/var/lib/postgresql/data/
        environment:
        - POSTGRES_DB=postgres
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
        ports:
        - "5432:5432"

volumes:
    postgres_data: